### ISSUE TITLE
[FEATURE] GPU Support?

### ISSUE THREAD

**Issue by invisible-walrus** [McCloudS/subgen#10]
any chance there will be a mode which enables utilizing the CUDA cores of an nvidia GPU?

**Comment by 2600box** [comment]
Wanted to voice my desire for this too. I use [whisper-timestamped](https://github.com/linto-ai/whisper-timestamped) to batch series, but being more integrated with plex would be great

**Comment by Wh1t3Rose** [comment]
Id also love this feature

**Comment by McCloudS** [comment]
Hey all,

I updated the dockerfile to potentially support this.  I don't have GPU at the moment to test, but will soon.  Take a look at some of the options and re-pull from dockerhub to try it out.

**Comment by McCloudS** [comment]
There is now a CUDA image that can be pulled from mccloud/subgen:cuda.  Try mapping your nvidia GPU and trying it.

**Comment by McCloudS** [comment]
Surprisingly, GPU support worked immediately.  I pulled the GPU image and my Tesla T4 did a 21 minute file in about 4.5 minutes.

Closed!
