### ISSUE TITLE
Hope can also automatically skip ASS subtitle files

### ISSUE THREAD

**Issue by Aliang-code** [McCloudS/subgen#106]
lots of the subtitle available online are format use ass. 
so hope can just add this
```
    elif skipifexternalsub and os.path.exists(get_file_name_without_extension(file_path) + f".{namesublang}.ass"):
        message = f"{file_path} already has an external {namesublang} subtitle created for this, skipping it"
```

**Comment by McCloudS** [comment]
Fringe case, but I added it.  I've literally never had a .ass downloaded from on online source (outside of it being bundled with the file).

https://github.com/McCloudS/subgen/commit/6029745329cb63ea0f681681e35dfdc53dbc4bdb
