### ISSUE TITLE
Transcription done, but no srt file

### ISSUE THREAD

**Issue by sahara101** [McCloudS/subgen#109]
Hello, 

I tried to use the container to make a subtitle for a movie. I have added the connection via bazarr

INFO:root:Bazarr transcription is completed, it took 271 minutes and 58 seconds to complete.
File subgen.env not found. Using default values.File subgen.env not found. Using default values.
INFO:     192.168.192.1:41410 - "POST /asr?task=transcribe&language=en&output=srt&encode=false HTTP/1.1" 200 OK

So it finished, but no srt file to be seen. If I go again through bazarr to download the sub, it starts transcribing again. 

Thanks!

**Comment by McCloudS** [comment]
What does your bazarr log show and what are your bazarr timeout settings?  If you exceed the timeout, bazarr will discard the subtitle.

**Comment by sahara101** [comment]
Yes, I had a bazarr provider error. Ah I thought since the container log kept doing its job that it didn’t matter. Timeout is 60s. How much should I increased it?

**Comment by McCloudS** [comment]
Your transcription/translation timeout needs to be however long you think you need to finish a run.  In your case, at least 272*60 seconds.  If if it takes longer than what you have set, bazarr marks it as a failure.

**Comment by sahara101** [comment]
Understood. I am testing it now. Pitty that integrated GPU is not working :(

**Comment by sahara101** [comment]
Worked!
