### ISSUE TITLE
Unraid Install - Error: write /var/lib/docker/tmp/GetImageBlob1196720095: no space left on device

### ISSUE THREAD

**Issue by cjnunn88** [McCloudS/subgen#121]
I referred to the following links when attempting to install: 
https://github.com/McCloudS/subgen/issues/37
https://github.com/McCloudS/subgen#variables

No matter what I try, I can't get this to install in Unraid. I always get the same error:
![image](https://github.com/user-attachments/assets/351b2c2e-58c6-4d5b-834e-0542894f926b)

What I have tried:
- Create a new container from scratch
- Create a container from another template, then update the repository, variables, paths
- Modify an existing container with the repository, variables, paths 

Attempted Container Paths/Variables:
Repository
mccloud/subgen:cpu

Appdata
Container Path: /config
Host Path: /mnt/user/appdata/subgen/

Port
8090

WHISPER_MODEL
tiny|tiny.en|base|base.en|small|small.en|medium|medium.en|large-v1|large-v2|large-v3|large|distil-large-v2|distil-large-v3|distil-medium.en|distil-small.en

MODEL_PATH
Container Path: /root/.cache/subgen
Host Path: /mnt/user/appdata/subgen/

TRANSCRIBE_DEVICE
cpu

CONCURRENT_TRANSCRIPTIONS
1

WHISPER_THREADS
1

Note: I just want to use this with Bazarr, so I am not setting any Plex/Jellyfin settings.

**Comment by McCloudS** [comment]
Is your unraid docker image full?  If you used the default 25/50gb, this image can take up a large chunk of that.

**Comment by cjnunn88** [comment]
![image](https://github.com/user-attachments/assets/b73401d6-148e-49fe-9197-ce9383e12441)

I guess that's what I wasn't understanding. I still haven't totally figured out Unraid.

I thought it would install to the appdata path, and I have over 200GB free on my cache drive.

Would you mind helping me figure this out?

How do I increase the image size? 

Where is the setting for where is the image stored?

![image](https://github.com/user-attachments/assets/b180ec68-4408-4ac1-a611-eeaabecdbd16)

**Comment by McCloudS** [comment]
https://www.reddit.com/r/unRAID/s/pBz80KGTe7

Essentially, stop docker service, go to advanced docker settings and pick a larger number.

**Comment by cjnunn88** [comment]
Thanks. I got it to install. Now I just have to figure out how to get Bazarr to connect
![image](https://github.com/user-attachments/assets/3ca2cd94-95c1-4c02-8cab-27daa5349931)

**Comment by McCloudS** [comment]
You’re probably missing your docker setting port mapping of 8090 to 8090.

**Comment by cjnunn88** [comment]
![image](https://github.com/user-attachments/assets/04905b4b-6c6c-496a-87e1-29fe61725a58)

I don't understand what's happening?

![image](https://github.com/user-attachments/assets/22d06a01-b112-469f-b4d8-4a11446d98ea)

**Comment by McCloudS** [comment]
If you’re changing it from the default port of 9000, you have to use the variable  WEBHOOKPORT

**Comment by cjnunn88** [comment]
Thanks. I didn't know the port changed. It connected. Trying it out now
