### ISSUE TITLE
How do I configure the Standalone version with no webinterface?

### ISSUE THREAD

**Issue by ThatRed** [McCloudS/subgen#122]
Hello @McCloudS,

I'm trying to install subgen in an Lxc Container, but since you removed the webui, I have no idea how to configure it. Can you please point me in the right direction how to do it?

Thanks in advance.

**Comment by McCloudS** [comment]
Define the environment variables you want to use/change in a script.  

https://www.tutorialspoint.com/unix/unix-using-variables.htm

**Comment by ThatRed** [comment]
Thank you for your answer. At the moment I figured out, that I can use subgen.env as a config file. That made it more convenient for me. 

How do I handle a path with blanks in it? Using "" at the beginning and end didn't work.

**Comment by McCloudS** [comment]
What’s the example of what you are trying to set?

**Comment by ThatRed** [comment]
I just figured it out: 
I went through the file system with cd to a show that had no english subs, to get the path, it showed the path for example of /media/TVShows/This is a test (1999) like /media/TVShows/This\ is\ a\ test\ \(1999\) and I copied it in like that. This did not work at all.
But when i put it in with all the blank/spaces like TRANSCRIBE_FOLDERS=/media/TVShows/This is a test (1999) it just worked. Sometimes it's just that easy ;)
