### ISSUE TITLE
webui configuration removed?

### ISSUE THREAD

**Issue by loopy321** [McCloudS/subgen#123]
It seems the webui configuration was removed.  
When I open port 9000 I get the following message:

```
// 20241012171546
// http://localhost:9000/

[
  "The webui for configuration was removed on 1 October 2024, please configure via environment variables or in your Docker settings."
]
```
Should I just set the following variables in subgen.env?
![image](https://github.com/user-attachments/assets/7776b309-5751-4949-a1dc-cce14e7c2d2d)

**Comment by McCloudS** [comment]
Yes, set them via the .env file or use docker env variables if appropriate.
