### ISSUE TITLE
Converting an 8-hour video will result in an abnormal exit from the program, and it should be loaded in batches

### ISSUE THREAD

**Issue by zzz583974851** [McCloudS/subgen#124]
Converting an 8-hour video will result in an abnormal exit from the program, and it should be loaded in batches

**Comment by McCloudS** [comment]
You're probably running into a memory issue then.  No plan to chunk files for processing at this point, unless someone submits a PR.

**Comment by zzz583974851** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
