### ISSUE TITLE
Versioned Docker images

### ISSUE THREAD

**Issue by Mrtenz** [McCloudS/subgen#128]
It'd be great if you could publish versioned Docker images, so `v1.2.3` or `v1.2.3-cpu` (as well as the current `cpu`, `latest`, etc.). This makes it easier for automated dependency management tools to update the image.

**Comment by McCloudS** [comment]
Updated to match the subgen.py versions.  Open to a different naming scheme if it makes sense.  

https://hub.docker.com/repository/docker/mccloud/subgen/tags

**Comment by Mrtenz** [comment]
Perfect, thanks!
