### ISSUE TITLE
Existing subtitles not detected when using `/batch` endpoint with `forceLanguage`

### ISSUE THREAD

**Issue by Mrtenz** [McCloudS/subgen#130]
It seems that when using `/batch` with `forceLanguage` set, Subgen doesn't detect existing subtitles, and will queue all files again.

I'm calling `/batch` with `directory=/path/to/folder` and `forceLanguage=nl` (since I know the content is in Dutch). I configured Subgen with `TRANSCRIBE_OR_TRANSLATE=translate` and `NAMESUBLANG=en` so the generated subtitles are translated to English, and named like `episode.subgen.large-v3.en.srt`. The logs show that no subtitle for "nl" was found, and it queues everything again.

My guess is that it has to do with `forceLanguage` in combination with `TRANSCRIBE_OR_TRANSLATE=translate`. Maybe Subgen doesn't expect that the output is English when checking for existing subtitles?

**Comment by McCloudS** [comment]
Yeah, you're right.  The logic is messy and was written with the assumption that you were generating subtitles that didn't have the subgen name.  I think I can write a quick fix.

**Comment by McCloudS** [comment]
Give it a shot if you want to pull the new version with `UPDATE = True`.  I don't have a good use case to test it, so you're the guinea pig.

**Comment by Mrtenz** [comment]
Looks like this fixes it, thanks! Can you publish a new version to Dockerhub as well?

**Comment by McCloudS** [comment]
Building the docker images now.
