### ISSUE TITLE
Plex not detecting generated subtitles

### ISSUE THREAD

**Issue by MediaMoots** [McCloudS/subgen#131]
due to

`subextension =  f".subgen.{whisper_model.split('.')[0]}.{namesublang}.srt"
subextensionSDH =  f".subgen.{whisper_model.split('.')[0]}.{namesublang}.sdh.srt"`

the .subgen.model* postfix is causing plex to not detect the srt
https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/#:~:text=Subtitle%20Language%20Settings-,External%20Subtitle%20Files,-There%20are%20many

it seems plex has a very strict naming scheme?
Or is there a config on plex i'm missing.
Thanks!

**Comment by McCloudS** [comment]
I’ll have to look later.  Plex sees all of mine with aa.subgen.medium.

**Comment by MediaMoots** [comment]
Weird, my srt generates as

FILENAME.subgen.medium.en.srt

with the lang code at the end.

i changed it to FILENAME.en.subgen.medium.srt and it didnt find it either

**Comment by MediaMoots** [comment]
using aa does not work either

**Comment by McCloudS** [comment]
I misspoke.

**Comment by McCloudS** [comment]
It

**Comment by MediaMoots** [comment]
Could try these repro steps

Create a Library of the "Other" type

Use a random non movie video file
![image](https://github.com/user-attachments/assets/2d1b1611-332b-41ff-8873-a5571a32085a)

**Comment by MediaMoots** [comment]
figured it out, i needed to use these exact settings
![image](https://github.com/user-attachments/assets/b00be96b-5697-44a8-80d9-454d51f0ea0b)

then subs worked
