### ISSUE TITLE
Blacklist for language

### ISSUE THREAD

**Issue by syue87** [McCloudS/subgen#132]
I only want to generate subtitle for languages I don't speak. It would be nice to have an option to skip languages I understand.

**Comment by McCloudS** [comment]
Can you give me an example?  Whisper can only translate into English or transcribe into itself.

**Comment by syue87** [comment]
Yea, since I do speak English, I want to translate all languages I don't speak into English. I'm using your software for generating subtitles for videos with languages I don't understand. Since most of the videos in my library is in language I understand, having a blacklist would greatly reduce the time to transcribe my library with the TRANSCRIBE_FOLDERS option.

**Comment by McCloudS** [comment]
Meaning you want an option to skip files that have X audio language (English for you)?

That should be possible.

**Comment by syue87** [comment]
Yes, and preferably a list since I do speak a few languages, I don’t need translation for any of the languages I don’t speak. Thanks.

**Comment by McCloudS** [comment]
Check out `SKIP_LANG_CODES` in the readme.  Should be what you're looking for.  I only tested it a bit.
