### ISSUE TITLE
[Feature Request] Provide a way to indicate when a monitored folder (or items in there) are finished processing

### ISSUE THREAD

**Issue by zorbaTheRainy** [McCloudS/subgen#136]
Maybe I am missing this (and I hope I am)

I need a way for subgen to alert another program when subgen has finished processing (either finished the subtitle or skipped the file).  Is there a way to do this?

The is `http://1.2.3.4:9000/ststaus` but that really only gives the version numbers of subgen and its parts.

As a new feature, could I set a listening webhook ENV and have subgen alert me when it has processed a file with an audio stream?
I mean it does need some filters, or else I'd get webhook notifications for *.jpg and *.nfo files.  

Is there an easier way to do this that I am missing?

Thanks

**Comment by McCloudS** [comment]
No, there really isn’t currently a way to do this unless you had another program/container monitor the log output.  What’s the use case?

**Comment by zorbaTheRainy** [comment]
The use case is being part of a workflow.

1. Sonaar/Radaar downloads a movie and puts it in staging area
2. Subgen processes the movie (either creating an *.srt or nothing if the subtitle stream already exists)
3. Handbrake re-encodes the movie, removing unwanted stuff.
4. mkvmerge adds the *.srt as an embedded stream (if it exists)
5. Processed file is input into plex/emby/jellyfin

The workflow branches for lang1, lang2, and lang_other.
Processing is done by moving the file to the a monitored folder (as it used to be a manual process).
It is using multiple instances (with different settings) of subgen, and handbrake uses different presets based on the monitored folder.

I am having a hard time with knowing when #2 (subgen) ends.  
I don't' see in the output log a note if the file is skipped due to existing subtitles.

My thoughts (and I am open to better wisdom), I could
1. Look for new srt files and the see when they stop growing, and if none are seem after a time out assume the file was skipped.
2. Monitor the docker log, but  I don't' see in the output log a note if the file is skipped due to existing subtitles. (this seems like a hassle)
3. Always submit the file via the ASR webhook, but this means I should do the checking to see if the desired subtitle stream already exists.

I am leaning to #3, but I don't know how to set the settings via ASR.  
I have multiple instances with different settings (ports 9100, 9101, 9102).  So, I do use different ENVs now

How does the ASR webhook interact with the container's ENVs.

**Comment by McCloudS** [comment]
How are you running this now?  Which function inside subgen are you using?

With DEBUG=True it states whether it skipped it or not: https://github.com/McCloudS/subgen/blob/67660dda6306dbb0220c091de1b30f2eeb8d42c3/subgen.py#L521

You also might have luck use post/pre-processing as a part of the Bazarr process.

**Comment by zorbaTheRainy** [comment]
Apparently, for some reason, my subgen was not running in unbuffered mode.

So, I was not getting the log entries.  

I'll close this

Thanks again
