### ISSUE TITLE
Transcribed even though I set it to translate.

### ISSUE THREAD

**Issue by HyperrJedi** [McCloudS/subgen#139]
I played an episode in Turkish, and I didn't notice in the start, but after it finished generating, the subtitles were in Turkish, instead of English. The only change I did was change the model from "medium" to "large-v3-turbo". Below is my compose
```
services:
  subgen:
    container_name: subgen
    image: mccloud/subgen
    runtime: nvidia
    network_mode: bridge
    ports:
      - 9000:9000
    volumes:
      - /mnt/drive/Jellyfin/Shows:/media/shows
      - SubgenModels:/subgen/models
    environment:
      - WHISPER_MODEL=large-v3-turbo
      - WHISPER_THREADS=2
      - PROCADDEDMEDIA=False
      - PROCMEDIAONPLAY=True
      - NAMESUBLANG=en
      - SKIPIFINTERNALSUBLANG=eng
      - JELLYFINTOKEN=89f7890e371649cf854ec0879e3e5e8c
      - JELLYFINSERVER=http://192.168.1.64:8096
      - WEBHOOKPORT=9000
      - CONCURRENT_TRANSCRIPTIONS=2
      - WORD_LEVEL_HIGHLIGHT=False
      - DEBUG=True
      - USE_PATH_MAPPING=False
      - PATH_MAPPING_FROM=/tv
      - PATH_MAPPING_TO=/Volumes/TV
      - TRANSCRIBE_DEVICE=gpu
      - CLEAR_VRAM_ON_COMPLETE=False
      - MODEL_PATH=./models
      - UPDATE=False
      - APPEND=False
      - USE_MODEL_PROMPT=False
      - CUSTOM_MODEL_PROMPT=
      - LRC_FOR_AUDIO_FILES=True
      - CUSTOM_REGROUP=cm_sl=84_sl=42++++++1
      - TRANSCRIBE_OR_TRANSLATE=translate
      - DETECT_LANGUAGE_LENGTH=360
      - FORCE_DETECTED_LANGUAGE_TO=tr
      - SKIPIFEXTERNALSUB=True
    tty: true
volumes:
  SubgenModels:
    external: true
networks: {}

```

Why is this? Thanks!

**Comment by McCloudS** [comment]
Fair to assume you're using the Jellyfin integration and not Bazarr?

**Comment by HyperrJedi** [comment]
> Fair to assume you're using the Jellyfin integration and not Bazarr?

Yes, using the webooks within Jellyfin

**Comment by McCloudS** [comment]
Is it consistent?  The fact that it knows it's Turkish and is translating, obviously means it should be outputting English.  And reverting to a non-turbo model the issue goes away?

**Comment by HyperrJedi** [comment]
I will check rn. One with medium and another with large-v3-turbo again. See ya in an hour i guess

**Comment by McCloudS** [comment]
Models can behave strangely and sometimes get stuck in odd loops or not actually translate and just transcribe.  If it's consistent, you could maybe 'trick it' by using kwargs to set an initial_prompt like: `SUBGEN_KWARGS={'initial_prompt': 'Hello, welcome to my lecture.'}`

**Comment by HyperrJedi** [comment]
Add this as an environment variable? And exactly this: `SUBGEN_KWARGS={'initial_prompt': 'Hello, welcome to my lecture.'}`?

**Comment by McCloudS** [comment]
Correct.  I haven't checked it in a while, but it should still work.

**Comment by HyperrJedi** [comment]
Ok I'll first try other models, then this initial prompt and let you know what happens.

**Comment by McCloudS** [comment]
The settings aren't deterministic, so you'll get slightly different results every time.

**Comment by HyperrJedi** [comment]
Damn, maybe i just got the 1/10 chance. Lets see. Thanks for the help

**Comment by HyperrJedi** [comment]
After trying again with medium, the large-v3-turbo, medium created the srt in English, while turbo, again, transcribed it to Turkish. I also wasn't able to get the kwargs thing to work, although I'm probably missing something. Could this just be an issue with the model?

**Comment by McCloudS** [comment]
Could be a model error, as the implementation in subgen didn’t change, it was implemented upstream in faster-whisper and stable-ts.  Sorry, not sure what to do.

**Comment by HyperrJedi** [comment]
Yeah, no problem. So would this be an issue with faster-whisper and stable-ts, or some compatability thing in subgen? Or maybe something else... thanks for the help anyways!

**Comment by McCloudS** [comment]
It's likely in the model or faster-whisper if anywhere, Subgen didn't make any changes to code to support it, only the dependencies.
