### ISSUE TITLE
Google translations feature

### ISSUE THREAD

**Issue by haimca** [McCloudS/subgen#141]
Adding #127 Google translation to different languages based on the English transcribed file.

**Comment by McCloudS** [comment]
I’ve been thinking a bit and am choosing not merge it.  Ultimately the issue is I can’t maintain functionality I can’t or won’t use, nor have the ability to test (English only speaker). I do appreciate the effort though.

**Comment by haimca** [comment]
I understand, but it's a really useful feature for people who don't English. I've being using it for a while now and it's working perfectly. 
There is no need to speak other languages since it's Google translation module doing all the work. 
I'm just suggesting it as an option for  whom ever wants it.
Anyway thank you for this great project.
