### ISSUE TITLE
Can subgen run on CUDA12.2

### ISSUE THREAD

**Issue by wuzz2zy** [McCloudS/subgen#151]
P4 only supports up to 12.2

**Comment by McCloudS** [comment]
My P4 is running with zero issues in the docker image.  What is the problem?

![image](https://github.com/user-attachments/assets/143c90ed-1ebf-4d16-9b51-f9cfd40902cc)

**Comment by wuzz2zy** [comment]
VGPU？

**Comment by wuzz2zy** [comment]
ok，i will try it now
