### ISSUE TITLE
Incorrect IP being returned from Plex

### ISSUE THREAD

**Issue by Schnoopie-Doopie** [McCloudS/subgen#157]
I guy's,

Im trying to set this up to automatically generate subtitles for non-English sections of movies and TV Shows.

I am running on unraid and have setup the plex and Tautulli webhooks and done some path mappings. My container is assugned ip of 10.1.0.220/23 and plex is 10.1.1.9. Bazarr is 10.1.1.220 and have setup the provider and tests to be ok.

The issue im having is when Plex sends a webhook I get an error:
``` INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
ERROR:root:Failed to process Plex webhook: HTTPConnectionPool(host='192.168.1.111', port=32400): Max retries exceeded with url: /library/metadata/33708 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14fcc92ca410>: Failed to establish a new connection: [Errno 113] No route to host'))
INFO:     10.1.1.9:60672 - "POST /plex HTTP/1.1" 200 OK
INFO:     10.1.1.9:60672 - "POST /plex HTTP/1.1" 200 OK
INFO:     10.1.1.9:60958 - "POST /plex HTTP/1.1" 200 OK
INFO:     10.1.1.218:50372 - "POST /tautulli HTTP/1.1" 200 OK
ERROR:root:An error occurred while checking the file with pyav: 
INFO:     10.1.1.218:50508 - "POST /tautulli HTTP/1.1" 200 OK
INFO:     10.1.1.9:33540 - "POST /plex HTTP/1.1" 200 OK
ERROR:root:Failed to process Plex webhook: HTTPConnectionPool(host='192.168.1.111', port=32400): Max retries exceeded with url: /library/metadata/33708 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x14fcc93407c0>: Failed to establish a new connection: [Errno 113] No route to host'))
INFO:     10.1.1.9:33516 - "POST /plex HTTP/1.1" 200 OK 
```
My compose file is:

```services:
  subgen:
    container_name: subgen
    tty: true
    image: mccloud/subgen
    environment:
      TZ: Australia/Brisbane    
       - "WHISPER_MODEL=medium"
       - "WHISPER_THREADS=4"
       - "COMPUTE_TYPE=auto"
       - "PROCADDEDMEDIA=True"
       - "PROCMEDIAONPLAY=True"
       - "NAMESUBLANG=aa"
       - "SKIPIFINTERNALSUBLANG=eng"
       - "PLEXTOKEN=secret"
       - "PLEXSERVER=http://10.1.1.9:32400"
       - "WEBHOOKPORT=9000"
       - "CONCURRENT_TRANSCRIPTIONS=2"
       - "WORD_LEVEL_HIGHLIGHT=False"
       - "DEBUG=True"
       - "USE_PATH_MAPPING=True"
       - "PATH_MAPPING_FROM=/share/Videos"
       - "PATH_MAPPING_TO=/Videos"
       - "PATH_MAPPING_FROM=/share/Video-Archive"
       - "PATH_MAPPING_TO=/Video-Archive"       
       - "TRANSCRIBE_DEVICE=cpu"
       - "CLEAR_VRAM_ON_COMPLETE=True"
       - "MODEL_PATH=./models"
       - "UPDATE=False"
       - "APPEND=False"
       - "USE_MODEL_PROMPT=False"
       - "CUSTOM_MODEL_PROMPT="
       - "LRC_FOR_AUDIO_FILES=True"
       - "CUSTOM_REGROUP=cm_sl=84_sl=42++++++1"
       - "DETECT_LANGUAGE_LENGTH=180"
       - "ENCODE=True"
    volumes:
      - /mnt/remotes/192.168.4.9_Videos:/Videos:rw,slave 
      - /mnt/remotes/192.168.4.9_Video-Archive:/Video-Archive:rw,slave    
      - /mnt/remotes/192.168.4.9_Videos:/share/Videos:rw,slave 
      - /mnt/remotes/192.168.4.9_Video-Archive:/share/Video-Archive:rw,slave      
    networks:
      br1:
        ipv4_address: 10.1.0.220      
    ports:
       - "9000:9000"       
networks:
  br1:
    external: true   
```
I can ping the plex server from the container

![image](https://github.com/user-attachments/assets/aa24ff22-4033-41a0-9d13-3dc563533c4a)

Any help would be great

**Comment by McCloudS** [comment]
You’ll need to set your plex ip address and token if using that.  You’re using the default of 192.168.1.111, which is my plex ip.

**Comment by Schnoopie-Doopie** [comment]
> You’ll need to set your plex ip address and token if using that. You’re using the default of 192.168.1.111, which is my plex ip.

Thanks for the quick response. I did set the Plex IP as below. Any other ideas? 

<img width="266" alt="image" src="https://github.com/user-attachments/assets/decfc5a8-1bcc-4345-9687-37a499cddbee" />

**Comment by McCloudS** [comment]
You said you have tautulli configured too?  What does your tautulli show?  They are a bit more reliable than plex webhooks.  They also don’t require a token.

**Comment by McCloudS** [comment]
The fact that you’re seeing calls to 192.168.1.111 shows an issue elsewhere, as that’s the default setting, so it’s not recognizing yours.

**Comment by Schnoopie-Doopie** [comment]
> You said you have tautulli configured too? What does your tautulli show? They are a bit more reliable than plex webhooks. They also don’t require a token.

I get a different error with Tautulli

![image](https://github.com/user-attachments/assets/03ec38a4-4692-4db0-b583-e996fe1edb9c)

**Comment by McCloudS** [comment]
Try debug to true to give a bit more fidelity to the errors.

**Comment by Schnoopie-Doopie** [comment]
> Try debug to true to give a bit more fidelity to the errors.

Yeah I have the debug set to true but this is all im seeing

<img width="220" alt="image" src="https://github.com/user-attachments/assets/66233195-aa6c-4b55-a303-04a1a5e614d1" />

**Comment by McCloudS** [comment]
You don’t want more than one “integration” configured.  So if bazarr meets your requirements and works, I would leave it at that.

**Comment by Schnoopie-Doopie** [comment]
> You don’t want more than one “integration” configured. So if bazarr meets your requirements and works, I would leave it at that.

I have Bazarr saying its working, as in its saying it Good in the providers status but have not see or been able to trigger it to do anything. As for Plex\Tautulli webhook, i thought this woudl be a better way to go. Ill use whichever works but agree I only want the video analyzed once

**Comment by McCloudS** [comment]
In that case, look at your sonarr and radarr settings in bazarr and make sure your score is about 50.  The whisper provider scores low so literally any other provider will outscore it.  In bazarr, unless you manually pick whisper, it will always pick the highest scoring provider.

**Comment by Schnoopie-Doopie** [comment]
> In that case, look at your sonarr and radarr settings in bazarr and make sure your score is about 50. The whisper provider scores low so literally any other provider will outscore it. In bazarr, unless you manually pick whisper, it will always pick the highest scoring provider. If you can’t figure out the bazarr portion (and prefer it), hop in the bazarr discord for help troubleshooting.
> 
> if I had to guess, your other tautulli and plex errors have to do with windows filesystems and trying to do docker in it. (Only a guess)

Thanks mate, I have changed the scores to 50 for both Sonar and Radar and have tried again. It doesnt look like it is triggering subgen when doing a manual scan for a single episode. It there a way I can force it to try?

![image](https://github.com/user-attachments/assets/c32bb1f0-4c1d-4178-9c67-e3e93132945b)

**Comment by McCloudS** [comment]
Are you able to do a manual search and select whisper?  It will always be in the bottom. 
![image](https://github.com/user-attachments/assets/1df97b60-914f-4990-ab59-4cfb1d99256d)

**Comment by Schnoopie-Doopie** [comment]
> Are you able to do a manual search and select whisper? It will always be in the bottom. ![image](https://private-user-images.githubusercontent.com/64094529/397957882-1df97b60-914f-4990-ab59-4cfb1d99256d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MzI3NzgsIm5iZiI6MTczNDgzMjQ3OCwicGF0aCI6Ii82NDA5NDUyOS8zOTc5NTc4ODItMWRmOTdiNjAtOTE0Zi00OTkwLWFiNTktNGNmYjFkOTkyNTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDAxNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NGFlODFlMGQ5NDZhN2U4YzUxYWQyM2Y2NzFjYjY5YWQ4NzlkODc1ZGI2NmIwMzQyMDUyM2U3NDk4MGM2MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lhrhilVER9-3LJtulezBZWGc7kHXGCGR5zJ6mJNi94o)

No im not able to select a search provider. I runnign the latest release

![image](https://github.com/user-attachments/assets/8d0902b0-9ee1-4ec9-aba7-420ccc10babd)

**Comment by McCloudS** [comment]
If you can’t scroll to the right of the whisperai provider to download/ pick it, then that may be a bazarr issue.  But at least bazarr sees it as a provider.  Again, everything else out scores it, so in your current configuration, bazarr would never pick the whisper provider automatically.
