### ISSUE TITLE
Feat: Create subtitles for entire season/show moving forward, not just current episode

### ISSUE THREAD

**Issue by ponchohoncho** [McCloudS/subgen#158]
Hello! I have a large TV library with many shows that don't have subtitles. I don't know that I want to sic bazarr on it, generating subtitles for media that might never get watched. For the shows that do need subs AND people watch, I'd like to proactively generate subs for the rest of the season instead of just the current ep.

The proposed workflow would be:

1. Get notice from Tautiulli/Plex/etc (not Bazaarr) about a new piece of media being watched.
2. Find that no subtitles are present
3. Create subtitles for that episode
4. Look forward at next eps and add those to a queue to generate automatically. Do this for the rest of the season
5. Optionally, go forward to process future seasons, or work backwards through previous seasons to catch up too.

I think this would help make a seamless viewing experience where subgen could generate the next episode's subtitles while you're watching the first and you wouldn't have to wait for them to be generated for each episode upon play start.

**Comment by McCloudS** [comment]
Totally agree that this would be nice.  I'll put it in the backlog and see if I can chew on it when I have free time.  

What's your aversion using Bazarr to fill them?

**Comment by McCloudS** [comment]
Just added this, take a look at the new entries in the readme for PLEX_QUEUE_NEXT_EPISODE and PLEX_QUEUE_SERIES

**Comment by ponchohoncho** [comment]
Super cool, thank you! The Bazarr setup seemed odd because you had to lower the quality score so low to get it to trigger the Whisper generation. It seemed like it would just get really bad subs online that way, and only sometimes trigger subgen to create them.

I'd love the Tautulli support! I pushed a show's worth of subs manually, and they're fantastic! What a cool project. Thank you!

**Comment by McCloudS** [comment]
> > Just added this, take a look at the new entries in the readme for PLEX_QUEUE_NEXT_EPISODE and PLEX_QUEUE_SERIES. More work will have to be done later to support it for Tautulli, Emby, or Jellyfin.
> 
> Just checking in on this. I also have a large library and would like to be able to only generate a subtitle for a specific episode, season or complete series. I use Emby though and I haven't seen any indication that this specific request will work with Emby?

Sorry, it doesn’t work with Emby, and to be honest, I’ll probably not get around to it.
