### ISSUE TITLE
Evaluate use of Whisper-Jax for more Speed

### ISSUE THREAD

**Issue by semigoro** [McCloudS/subgen#20]
Hello,

i found your repo, awesome idea, was looking some time for something like this.
this is a little suggestion. i came across this repo [Whisper-Jax](https://github.com/sanchit-gandhi/whisper-jax). The Dev says its fast, 70x faster than normal whisper on tpu. i know normally you have no tpu, but the benchmarks in the repo show also improvements on gpu. you can give it a shot on [this hugginface space](https://huggingface.co/spaces/sanchit-gandhi/whisper-jax) from the same dev.

Maybe you can look into it.
Would be awesome if you can make it even faster as it is now. 
Thanks for your tool and the time you invest in it ;)

- semigoro

**Comment by McCloudS** [comment]
It appears whisper-jax is still missing feature necessary to do accurate subtitles via stable-ts or whisperX.  

See: https://github.com/jianfch/stable-ts/issues/142
