### ISSUE TITLE
Install issue "No module named 'fastapi'"

### ISSUE THREAD

**Issue by hhjuhl** [McCloudS/subgen#25]
I´ve been trying to set up the docker image on a synology NAS. I keep getting this error. (See below). I'm using docker compose and I've tried all sorts of variations of the repo´s docker-compose.yml

USER@SERVER:/volume1/docker/appdata$ sudo docker-compose up subgen
[+] Running 1/0
 ⠿ Container subgen  Created                                                                                                                                               0.0s
Attaching to subgen
subgen  | Traceback (most recent call last):
subgen  |   File "/subgen/./subgen.py", line 29, in <module>
subgen  |     from fastapi import FastAPI, File, UploadFile, Query, Header, Body, Form, Request
subgen  | ModuleNotFoundError: No module named 'fastapi'
subgen exited with code 1

**Comment by McCloudS** [comment]
Thanks for the headsup, my dev 'environment' is me on an iPad in bed, so I make mistakes often.  I inadvertently removed the package install portion in the script, it's now back in.  If you mapped your volume, you can manually replace subgen.py or just re-pull the docker image.
