### ISSUE TITLE
Docker-compose issue

### ISSUE THREAD

**Issue by notarobot63** [McCloudS/subgen#29]
Hello,
The Docker build does not seems to end, Here are the last lines of the logs:
```
whisper has been successfully installed.

Traceback (most recent call last):

  File "/subgen/./subgen.py", line 40, in <module>

    import stable_whisper

ModuleNotFoundError: No module named 'stable_whisper'
```
Any idea ?

**Comment by McCloudS** [comment]
I don't... the Dockerfile currently builds fine and stable-ts is the package that needs 'import stable_whisper'.  Are you building the dockerfile or pulling it from dockerhub (via docker-compose)?  My only guess if you're building it yourself could be non-amd64 architecture throwing issues.

**Comment by notarobot63** [comment]
I'm pulling from docker-compose on a debian x64 VM.

-------- Message d'origine --------

**Comment by McCloudS** [comment]
That doesn't appear to be a dockerfile/docker-compose issue but an issue when the script is actually executed on start.  For whatever reason, that implies that the installation of stable-ts is failing.  You can try manually doing `pip3 install stable-ts` and see if it installs correctly.  I pulled a fresh image and mine spins up immediately with no issue.

**Comment by notarobot63** [comment]
I'll try tomorrow and let you know, thanks!

-------- Message d'origine --------

**Comment by McCloudS** [comment]
Spun up the same image on a different machine, fresh install.  No errors.

**Comment by notarobot63** [comment]
That's really weird, I tried with cpu or latest branches still the same:
Here is the docker-compose if that can help:
`version: '2'
services:
  subgen:
    container_name: subgen
    tty: true
    image: mccloud/subgen:latest
    environment:
       - "WHISPER_MODEL=medium"
       - "WHISPER_THREADS=4"
       - "PROCADDEDMEDIA=True"
       - "PROCMEDIAONPLAY=False"
       - "NAMESUBLANG=aa"
       - "SKIPIFINTERNALSUBLANG=fra"
       - "JELYFINTOKEN=token here"
       - "JELLYFINSERVER=http://jellyfin:8096"
       - "WEBHOOKPORT=8090"
       - "CONCURRENT_TRANSCRIPTIONS=2"
       - "WORD_LEVEL_HIGHLIGHT=False"
       - "DEBUG=False"
       - "USE_PATH_MAPPING=False"
       - "PATH_MAPPING_FROM=/tv"
       - "PATH_MAPPING_TO=/Volumes/TV"
       - "TRANSCRIBE_DEVICE=cpu"
       - "MODEL_PATH=."
    volumes:
       - "./tv:/tv"
    ports:
       - "8090:8090"
`

**Comment by McCloudS** [comment]
My last guess would be that your container doesn't have a valid network configuration and/or internet connection.  So when it tries to download the packages, they all fail, and so it can't import them.  You could troubleshoot by watching the output of the script run on container start, or getting a shell and trying to install the packages manually.

See: https://docs.docker.com/compose/networking/

**Comment by notarobot63** [comment]
The container has Internet access and downloads the packages without problem.
Anyway I skipped the docker way and used the script straight from the VM and it works, I guess there's an issue with the docker images or whatever. 
Great job anyway !
