### ISSUE TITLE
Setting up via Unraid

### ISSUE THREAD

**Issue by DMD770** [McCloudS/subgen#37]
I'm a bit loss on how to set this up via Unraid. I tried to do the add container, but it would not take any link repository. I get the idea how the file directory is supposed to be. but im just unable to add it via container if that make sense.

**Comment by McCloudS** [comment]
Here's a screenshot of mine... They should at least get you up and running.  If you aren't going to use a GPU, use mccloud/subgen:cpu.  Go to your Docker page, at the bottom there is an "Add container" button.  To add the "Host Keys" you just click "add another path, port, variable, label, or device" (at the bottom the Add Container page) and choose variable.  The variables you can change are at: https://github.com/McCloudS/subgen#variables


![image](https://github.com/McCloudS/subgen/assets/64094529/043644b2-d04d-4cde-ab3e-d86879ca073b)
![image](https://github.com/McCloudS/subgen/assets/64094529/7f1742d7-a3d0-44db-9f24-3412361b7c30)
![image](https://github.com/McCloudS/subgen/assets/64094529/9594359e-71a1-49b7-98f5-8d1e3ccd5699)

**Comment by DMD770** [comment]
THank you so much, now im having issue with Nvidia driver not being detected. but i know my unraid has it. so im assuming it is in the docker that need it?

**Comment by McCloudS** [comment]
I forgot to mention, assuming you have the unraid nvidia driver plugin installed, you need to edit the docker settings (same way you created it), enable advanced in the top right and add the command in the picture for GPU. 
![image](https://github.com/McCloudS/subgen/assets/64094529/55e073c2-f4f8-49cc-ae5c-a1ec9e76c72e)

Whether or not it’s working depends on which provider (Plex, Emby, Jellyfin, Bazarr, or Tautulli) you’re trying to use and which triggers (play or media add) you have configured via the environment variables.

**Comment by DMD770** [comment]
the GPU is now working, so i think it not doing anything because nothing has happened. im thinking it is the directory to tv/movies. I have attached a few of photo of my library in jellyfin, then setting in jellyfin container, and my subgen container. i think im supposed to have the setting from jellyfin library directory match the subgen?

Jellyfin Library 
![image](https://github.com/McCloudS/subgen/assets/128275268/29968019-3509-42e2-8ce2-c7699718b637)
Subgen Container 
![image](https://github.com/McCloudS/subgen/assets/128275268/592236aa-13e6-4d22-89f9-595918266ff0)
Jellyfin Container
![image](https://github.com/McCloudS/subgen/assets/128275268/32813b56-7ae3-45ec-ad19-bb5b677c93e1)

**Comment by McCloudS** [comment]
In subgen, you just need a single path, to match Jellyfin.  So it would be: host path /mnt/user/data/media and container path: /media

Make sure you have your Jellyfin address and API key set as well!

**Comment by DMD770** [comment]
jellyfis hook didn't work, so i went with bazaar because that was much simpler, and it worked almost right away after rebooting subgen. it seem doing the job. but do you know if using bazaar, will it automatically generate the subtile right away when scanning the disk?

**Comment by McCloudS** [comment]
It will be based on your bazarr settings and whether it’s able to find subs from other configured providers.  Whisper defaults to a static score that is low (I think 66), so most providers will outscore it.

**Comment by DMD770** [comment]
I saw that via bazaar website about whisper static score, so i scored it at 50 and it still doesn't "auto-download" the whisper. that is a odd behavior... but if you do it manually via interactive search and choose whisper it works.

**Comment by Alex-Lee-Myers** [comment]
Small addendum to the screenshot here is you need to put `mccloud/subgen:latest` for the repository if you want to use a gpu.

**Comment by McCloudS** [comment]
How do you have it configured?  You should be seeing your downloaded model folder at a minimum.

In the grand scheme, unless you’re looking to do something in that folder, you don’t really need to map it (unless you want persistent model storage between Docker image updates).

**Comment by Alex-Lee-Myers** [comment]
I'm currently getting [this](https://github.com/user-attachments/assets/89e7eb87-f03d-4ea4-971a-67cf76bfd277) in my logs and it won't start (due to [nothing in the appdata/subgen/ folder](https://github.com/user-attachments/assets/a3d01502-dce6-427c-8859-ddf8e105d0e9)).

Here is my full setup just in-case I missed a step in my configuration:
- ![Part 1](https://github.com/user-attachments/assets/a0f75fe2-9f49-41fa-804e-b68240979c32)
- ![Part 2](https://github.com/user-attachments/assets/e8c86718-565e-42ca-9162-fd7f151e691f)

**Comment by McCloudS** [comment]
Because your volume mount of /mnt/user/subgen is overwriting the file path necessary to run in the container.  I only use that for development purposes.  Recommend deleting that mount completely, an average user won't need it.

**Comment by Alex-Lee-Myers** [comment]
I believe I am [good to go now](https://github.com/user-attachments/assets/4c5b6cf1-62db-47d2-bdc3-869f25cb203f)! I am having other issues now, but seems like I should go ahead and move any further issues beyond setup to the [Discord](https://wiki.bazarr.media/Additional-Configuration/Whisper-Provider/). Thaks for the help on getting started!

**Comment by McCloudS** [comment]
Updated screenshots @ https://github.com/McCloudS/subgen/discussions/137
