### ISSUE TITLE
Allow adding a gap at the end of each sentence

### ISSUE THREAD

**Issue by ellisonpatterson** [McCloudS/subgen#38]
Generated subtitles disappear incredibly quickly compared to normal subtitles that you would see with media.

Once the person is done speaking, the subtitle immediately disappears and it's a little jarring.

Could an option to add x amount of time at the end of each line be added, so they don't immediately disappear?

Thank you!

**Comment by McCloudS** [comment]
If you can find an option in stable-ts or faster-whisper that can support
that, I can look into it.  Otherwise I'll close it, as that isn't subgen
specific.
