### ISSUE TITLE
Error: CUDA failed with error CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by 2600box** [McCloudS/subgen#40]
Hello,

I am trying to get this going on windows to use with Nvidia GPUs. 

The default `mccloud/subgen:cuda` image fails with 
```
subgen  | Installing whisper...
subgen  | Requirement already satisfied: whisper in /usr/local/lib/python3.10/dist-packages (1.1.10)
subgen  | Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from whisper) (1.16.0)
subgen  | WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
subgen  | whisper has been successfully installed.
subgen  | Traceback (most recent call last):
subgen  |   File "/subgen/./subgen.py", line 43, in <module>
subgen  |     import ffmpeg
subgen  | ModuleNotFoundError: No module named 'ffmpeg'
```

So I added `ffmpeg-python` to `subgen.py` and changed the Dockerfile.cuda to point to `./subgen/subgen.py` and was able to pass the error, but subsequently run into this cuda error upon attempting transcription:

`CUDA failed with error CUDA driver version is insufficient for CUDA runtime version`

I tried messing around with updates in the container, etc. but had no success.

Any advice to get cuda working? Is it related to building the container rather than using your image?

Thanks!

**Comment by McCloudS** [comment]
Working on the first issue.  For GPU on windows, take a look at: https://github.com/SYSTRAN/faster-whisper?tab=readme-ov-file#requirements

**Comment by 2600box** [comment]
Resolved with the latest changes by @McCloudS Thanks!
