### ISSUE TITLE
Non-cuda dockerfile has cuda image

### ISSUE THREAD

**Issue by lyfenwebos** [McCloudS/subgen#41]
So I wanted to use docker container and I noticed that recently non-cuda docker container was probably non intentionally swapped to the cuda image.
https://github.com/McCloudS/subgen/blob/main/Dockerfile#L1

**Comment by McCloudS** [comment]
It was done on purpose to simplify building.  While it will be slightly
larger on download, it shouldn’t impact anything.  Some of the packages
even in CPU only required cuda packages resulting in minimal space
savings.  Let me know if there are issues.

**Comment by lyfenwebos** [comment]
So setting `TRANSCRIBE_DEVICE: "cpu"` should be enough to use cpu? In my case it still tries to use cuda

**Comment by lyfenwebos** [comment]
Or it is okey that it is trying to load cuda, fails and throws an info/debug(?) message?
Below this debug message about cuda not available I have this block
`import ffmpeg-python`

**Comment by McCloudS** [comment]
Thank, I’ll take a look.  The default behavior should fail to CPU if no GPU is found.  What does it look like it’s doing?

**Comment by McCloudS** [comment]
Yeah, I’m troubleshooting that ffmpeg line now.  Sorry for the inconvenience.

**Comment by lyfenwebos** [comment]
Okey, then I suppose it is a duplicate and I'll be following regarding this in the neighboring issue

**Comment by McCloudS** [comment]
Confirmed that if no GPU is found, it will default to CPU without issue.
