### ISSUE TITLE
I don´t undertand how works

### ISSUE THREAD

**Issue by dboillos** [McCloudS/subgen#42]
I don't understand if something else needs to be configured. The logs are fine, the container receives the requests. The path mapping is corret. It is set to debug=true and no errors appear. The webhook in emby is configured with all options.  I don't understand. I need config anything else?

**Comment by McCloudS** [comment]
Is it actually 'working' and providing any subtitles?  Are you seeing anything in your media folders?  The logs should show any ongoing transcription if configured correctly.  I'm running my hooks through Tautulli, but Emby should look near identical to something like below (below doesn't have Debug on):
![image](https://github.com/McCloudS/subgen/assets/64094529/50fb0a3b-f95e-4412-b0d9-e4a36a0db1ff)

**Comment by McCloudS** [comment]
Closed.  No information provided.
