### ISSUE TITLE
'tuple index out of range' in logs when trying to transcribe local files.

### ISSUE THREAD

**Issue by Boyda-DBA** [McCloudS/subgen#45]
I have the docker setup to transcribe a folder of media. The log will show errors on many files and the error is always tuple index out of range. Some files seemingly work fine.

**Comment by McCloudS** [comment]
Can you provide the log?  Not tons of testing has been done on the local/folder transcription.

**Comment by McCloudS** [comment]
Alright, I'm taking a guess, and you had file names or paths with commas.  If that's the case, I just updated subgen.py to use a pipe '|' as the delimiter for the paths.

**Comment by Boyda-DBA** [comment]
Here is an example of the errors in logs on unraid.
![Screenshot 2024-02-05 140609](https://github.com/McCloudS/subgen/assets/122284392/79105f0d-ef57-41d7-a112-876c58cd150d)

**Comment by McCloudS** [comment]
What is your TRANSCRIBE_FOLDERS set to?

**Comment by McCloudS** [comment]
I swapped around some logic in subgen.py that might fix it.  You'll have to do a re-pull.  There is a chance that your path mapping is goofing up the directory pathing.  Before re-pulling the image, I would recommend removing both PATH_MAPPING_FROM and PATH_MAPPING_TO and trying it again.  That's typically only useful in a non-docker environment.

**Comment by Boyda-DBA** [comment]
After removing the variables mentiones it still shows the error, but only for a .nfo file. Will run this for a bit before repulling to confirm if it is the issue.
![image](https://github.com/McCloudS/subgen/assets/122284392/5ac76ee6-bfc3-4bde-8c3d-783a5ba359dd)

**Comment by McCloudS** [comment]
Bizarre... is_video_file checks the files to make sure they are a valid video container before trying to transcribe them.   It shouldn't even get to that point with an .nfo

**Comment by McCloudS** [comment]
I added some checking that should prevent the tuple index out of range.  If it continues to be an issue, try re-pulling and let me know.  Closing for now, just re-comment if you need help.

**Comment by Boyda-DBA** [comment]
Based on the logs video files are still being transcribed so I will leave it as up. Just seems to not be excluding the non video files for some reason.

I have a pretty low level understanding of python, but is it possible the path_mapping function is erroring out and returning an unexpected value?

**Comment by McCloudS** [comment]
To be honest, this was my first python project, so it's new to me too.  It shouldn't if it's set to false via USE_PATH_MAPPING.  I'm also struggling to understand why nfo and image files are passing the is_video_file check.  

I might need to do another update to remove the failed files from the queue, otherwise they'll stay there until container restart.

**Comment by Boyda-DBA** [comment]
Very cool first project. I will take a peak in my spare time and report my findings for what it's worth. Appreaciate the responses
