### ISSUE TITLE
anyway to force language in case of wrong whisper autodetection?

### ISSUE THREAD

**Issue by ndx1905-github** [McCloudS/subgen#47]
Hi

Thanks for the great work and very useful tool (I'm amazed that it works on my 2018 NAS)

Faster whisper sometimes picks the wrong language..
Is there a way to force the language?

Here is an example, it's French audio wrongly detected as English (score of .56)

![image](https://github.com/McCloudS/subgen/assets/64833823/d72e3b1d-010c-4529-962c-4be5b97a4acd)

I should pass the --language fr to faster-whisper. One way could probably be to add "FR" somewhere at the end of the file name right before the file extension?
https://github.com/openai/whisper/discussions/529

**Comment by McCloudS** [comment]
There is a way, but I haven’t exposed it.  I can look at that.  Whisper
only uses the first 30 seconds to detect audio.  So if there is little
audio or it’s mixed with English, it can guess wrong.

**Comment by McCloudS** [comment]
Take a look at the readme @ FORCE_DETECTED_LANGUAGE_TO and try to re-pull the image.  Let me know if it works!

**Comment by McCloudS** [comment]
Good to know that even with the misdetected language, it produces something passable.  Did you actually pull the new docker image instead of just restarting it?

**Comment by ndx1905-github** [comment]
Yes I redownloaded the image. Just did it again, same result. Still detects English.
But does the --language option change the language that is detected, or does it still detect English, writes that in the console and then the --language option forces faster-whisper to use FR even though EN was detected ?

**Comment by McCloudS** [comment]
It's passed the way that stable-ts and faster-whisper document.  And per https://github.com/SYSTRAN/faster-whisper/blob/f144e4c83d54f3c3304b6a75a3f563e5f84de6cf/faster_whisper/transcribe.py#L344 it shows that if a language is manually defined it shouldn't try to detect the language unless it's an English only model.  Any chance you're using the .en models?  Like medium.en instead of medium.

**Comment by ndx1905-github** [comment]
yes I'm sure I've selected medium, not medium.en
Also medium.en would probably produce garbage? but my output is still good

**Comment by McCloudS** [comment]
I'm a little puzzled as to why it's ignoring the language.  I'll play with it later if I have time, but it's comforting to know that it may not actually matter?

**Comment by McCloudS** [comment]
This is now fixed and I confirmed it will show as the correct forced language.  You can also navigate to http://subgenip:8090/docs in a browser and use the Batch option.
