### ISSUE TITLE
AA.srt not showing in Subtitle list in Plex.

### ISSUE THREAD

**Issue by Wh1t3Rose** [McCloudS/subgen#5]
Hello. I have this installed in Unraid. I can see in the live log it generating the subtitles, and I can see what the people are saying. 

I can also see the file it generates next to the episode file (EX NameOfEpisdoe.mkv.output.wav

However in Plex on my Shield TV and Plex app on PopOS, I do not see the AA.srt subtitle listed for me to select.

**Comment by McCloudS** [comment]
What's the full name of your media and subtitle?  For example, "Community - S03E18 - Course Listing Unavailable.subgen.large.aa.srt" shows up just fine on my Plex apps and the web browser.  

![image](https://user-images.githubusercontent.com/64094529/215570443-1b1f3aa2-5e4b-45af-8df0-f10a055e7a30.png)

**Comment by Wh1t3Rose** [comment]
Here is the live rolling log

![image](https://user-images.githubusercontent.com/4251482/215571924-5aa3e184-33f8-4008-b890-de14246ded0b.png)


I have 2 streams going. One is a remote user (RuPaul's Drag Race - S05E06 - Can I Get an Amen.mp4)

My stream is local and it is American Horror Story - S01E01 - Pilot.mkv

**Comment by McCloudS** [comment]
Have you actually had it generate/output a subtitle yet?  That log implies it just started processing the wav through the model.  On my setup, the medium model is about 45 seconds of processing per 60 seconds of media.

**Comment by McCloudS** [comment]
If you go to a media file on Tautulli, you can trigger a "Recently Added" from there.  That's how I did most of the testing.

![image](https://user-images.githubusercontent.com/64094529/215574873-393fcddc-d9e5-4a55-bdae-5d23022034e7.png)

**Comment by Wh1t3Rose** [comment]
Ok. I tested what you show. I did not see any activity in the live log for the new episode and I did not see it generate a .output.wav file for that episode. 

Is this because it is already creating a file for another episode? Can it do multiple transcodes at once?


![image](https://user-images.githubusercontent.com/4251482/215575748-dcc9272e-a048-455d-8ef1-8cf5141167ed.png)

**Comment by McCloudS** [comment]
I've done 3-4 simultaneously.  But if you're pegging your CPU, if might take longer than usual to actually extract and create the wav file.  I think most of the debug stuff is still in the script, so you should at least see that it "saw" a valid webhook.

**Comment by Wh1t3Rose** [comment]
Holy smokes! I have a 3950x and it is pegging all 16 cores at 100%!! hmmmm

**Comment by Wh1t3Rose** [comment]
Ok I can see it generated an srt now. I see it in the list and it works!

Thank you for explaining everything and being so repsonsive! I appreciate it! You have an asesome project here. 

![image](https://user-images.githubusercontent.com/4251482/215578162-10eddecf-5c49-4f38-9f1b-6f7c9ebcf934.png)
