### ISSUE TITLE
Almost working...on unraid

### ISSUE THREAD

**Issue by Maitresinh** [McCloudS/subgen#54]
What a wonderfull app. I've tried to add it on my Unraid server, usring plex and bazarr, to ger french and spanish subs.

What i've done sor far :

**1/ Use Docker compose with that file below. Downloaded and installed**

#docker-compose.yml
version: '2'
services:
  subgen:
    container_name: subgen
    tty: true
    image: mccloud/subgen
    environment:
       - "WHISPER_MODEL=medium"
       - "WHISPER_THREADS=4"
       - "PROCADDEDMEDIA=True"
       - "PROCMEDIAONPLAY=False"
       - "NAMESUBLANG=aa"
       - "SKIPIFINTERNALSUBLANG=fra"
       - "PLEXTOKEN=tokenhere"
       - "PLEXSERVER=http://plexserver:32400"
       - "JELLYFINTOKEN=token here"
       - "JELLYFINSERVER=http://jellyfin:8096"
       - "WEBHOOKPORT=8090"
       - "CONCURRENT_TRANSCRIPTIONS=2"
       - "WORD_LEVEL_HIGHLIGHT=False"
       - "DEBUG=True"
       - "USE_PATH_MAPPING=False"
       - "PATH_MAPPING_FROM=/tv"
       - "PATH_MAPPING_TO=/Volumes/TV"
       - "TRANSCRIBE_DEVICE=cpu"
       - "CLEAR_VRAM_ON_COMPLETE=True"
       - "HF_TRANSFORMERS=False"
       - "HF_BATCH_SIZE=24"
       - "MODEL_PATH=./models"
       - "UPDATE=False"
       - "APPEND=False"
    volumes:
      - /mnt/user/video/films
      - /mnt/user/video/series
    ports:
       - "9000:9000"

I'm not 100 % sure on the Volumes (addded the complete path) and path mapping from/too (my "series" volume is mapped under "TV" in Sonarr/Bazarr, but i don't know if subgen will find it

2 - I've addd it to bazarr with local server (127. ...) and open a port on my router.
i've added it too as a webhook

Anyway, when i search a sub with bazar, nothing is found. Same thing on plex.

Help ?

**Comment by Maitresinh** [comment]
If i would know how to get the logs, i could post it on the Whisper Discord...

**Comment by McCloudS** [comment]
You won’t need volume if you’re using Bazarr.  Your up address for the
whisper provider will be your unraid ip.  So for mine the full url is
http://192.168.1.111:9000

**Comment by Maitresinh** [comment]
thanks.

Changed in bazarr to http://192.168.1.111:9000/ (port is open)
Search on a serie : no subs founds.

do i have to borrow any volume in the .yml ?

**Comment by McCloudS** [comment]
What do your subgen logs say, and are you able to access `http://yourunraidip:9000/docs`?

**Comment by Maitresinh** [comment]
"You accessed this request incorrectly via a GET request.  See https://github.com/McCloudS/subgen for proper configuration"

**Comment by McCloudS** [comment]
That means the port is exposed and all good (and accessable).  Try your Bazarr again with it set to `http://yourunraidip:9000`

**Comment by Maitresinh** [comment]
Tested. Nothing found

Below the / doc
--------------
FastAPI
 0.1.0 
OAS 3.1
[/openapi.json](http://192.168.1.6:9000/openapi.json)
[default](http://192.168.1.6:9000/docs#/default)


GET
[/](http://192.168.1.6:9000/docs#/default/handle_get_request__get)
Handle Get Request


GET
[/detect-language](http://192.168.1.6:9000/docs#/default/handle_get_request_detect_language_get)
Handle Get Request


POST
[/detect-language](http://192.168.1.6:9000/docs#/default/detect_language_detect_language_post)
Detect Language


GET
[/emby](http://192.168.1.6:9000/docs#/default/handle_get_request_emby_get)
Handle Get Request


POST
[/emby](http://192.168.1.6:9000/docs#/default/receive_emby_webhook_emby_post)
Receive Emby Webhook


GET
[/asr](http://192.168.1.6:9000/docs#/default/handle_get_request_asr_get)
Handle Get Request


POST
[/asr](http://192.168.1.6:9000/docs#/default/asr_asr_post)
Asr


GET
[/jellyfin](http://192.168.1.6:9000/docs#/default/handle_get_request_jellyfin_get)
Handle Get Request


POST
[/jellyfin](http://192.168.1.6:9000/docs#/default/receive_jellyfin_webhook_jellyfin_post)
Receive Jellyfin Webhook


GET
[/webhook](http://192.168.1.6:9000/docs#/default/handle_get_request_webhook_get)
Handle Get Request


POST
[/webhook](http://192.168.1.6:9000/docs#/default/print_warning_webhook_post)
Print Warning


GET
[/plex](http://192.168.1.6:9000/docs#/default/handle_get_request_plex_get)
Handle Get Request


POST
[/plex](http://192.168.1.6:9000/docs#/default/receive_plex_webhook_plex_post)
Receive Plex Webhook


POST
[/tautulli](http://192.168.1.6:9000/docs#/default/receive_tautulli_webhook_tautulli_post)
Receive Tautulli Webhook


POST
[/batch](http://192.168.1.6:9000/docs#/default/batch_batch_post)
Batch


Schemas
Body_asr_asr_postExpand allobject
Body_detect_language_detect_language_postExpand allobject
Body_receive_emby_webhook_emby_postExpand allobject
Body_receive_jellyfin_webhook_jellyfin_postExpand allobject
Body_receive_plex_webhook_plex_postExpand allobject
Body_receive_tautulli_webhook_tautulli_postExpand allobject
HTTPValidationErrorExpand allobject
ValidationErrorExpand allobject

**Comment by McCloudS** [comment]
That shows subgen working properly, you just have a misconfiguration in Bazarr then.  What is your whisper-provider settings and how are you searching for subtitles?  Simple way is just a manual search to see if whisper is showing up.  You also may need to reset the providers if whisper is showed as failed.

**Comment by Maitresinh** [comment]
My  Whisper setting on bazarr

http://mylocalipunraid:9000
Connection/response timeout in seconds
5
Transcription/translation timeout in seconds
3600
Logging level

----------------

To look for the subs, i'm going to the serie detail (epsiodes), select one episode and look for subtiles. 
I've also done a global search

By the way, how do i use it under Plex ? Just looking for subs ?

**Comment by McCloudS** [comment]
Also if you don’t meet the minimum score, whisper will never run.  Bazarr sets it as a low static score so virtually anything can replace it.

**Comment by McCloudS** [comment]
Past that, you’ll have to go into the bazarr discord for support, as the subgen container is working and bazarr configuration stuff is beyond my knowledge.

**Comment by Maitresinh** [comment]
I'm doing the test on a show already in my plex, withtout subs (The Newsreader)

Provider "status" : good

thanks for your help anyway, i will ask @discord

**Comment by Maitresinh** [comment]
Last but not least : how can i get the logs ?

**Comment by McCloudS** [comment]
Here’s how mine looks in unraid: 
![image](https://github.com/McCloudS/subgen/assets/64094529/fb5c09e3-3dc8-42c4-a689-e6b2224dd622)

**Comment by Tuumke** [comment]
1. might want to remove the token for plex
2. volumes aren't mounted properly?
You have 
```
volumes:
- /mnt/user/video/films
- /mnt/user/video/series
```

While it should be something like:
```
  volumes:
    - /mnt/user/video/films:/filmes
    - /mnt/user/video/series:/series
```

Notice the ``` : ``` between left side (actual file path on system) and right side (mount point inside the docker)

**Comment by McCloudS** [comment]
User was trying to translate into unsupported language.

**Comment by Maitresinh** [comment]
yes i did :-
...and dicovered lingarr.

It seems it works for transcription.
Thanks fkor your time
