### ISSUE TITLE
How do I mount multiple drives?

### ISSUE THREAD

**Issue by terrificobjects** [McCloudS/subgen#59]
Hi,

So currently, I have Plex installed on Windows. I have Whisper ASR webservice installed in Docker. I use Bazarr, but I'd like to implement and play with this a bit.

That being said, I have multiple drives. All of them have a "Media" folder in them with subfolders "TV Shows", "Anime", "AnimeMovies", "Movies" and "Music". Plex is mapped to use TV Shows library with all of the "TV Shows" folders present inside "Media" on each drive.

So my question is how would I map this setup to a subgen Docker container in docker-compose.yml?

Thanks in advance for any help. Not sure if this is the right place for this.

**Comment by McCloudS** [comment]
Are you using this to replace the whisper-asr webhook in Bazarr (which it can do), or to use the plex webhook?

**Comment by terrificobjects** [comment]
My hope was to use the Plex webhook. Docker/Docker Desktop is running on the same Windows machine as Plex Media Server, Bazarr, Tautulli, Whisper ASR docker container and the other stuff like Sonarr, etc., and I am using WSL-Ubuntu on WSL2. I can see my drives in WSL2 as /mnt/d, /mnt/e, /mnt/g and so on.

**Comment by McCloudS** [comment]
To be honest, as it stands, I don’t think the docker container can exactly do what you want.  I didn’t really account for translating file paths from Linux to Windows. You would use path mapping, but I don’t have it set up to take multiple path substitutions.  If Plex was also in your docker, it would work with little configuration.

The simplest way would be to run the script in standalone mode (without Docker) on Windows.

**Comment by terrificobjects** [comment]
That's not a problem at all. I'll try the standalone mode. Thanks for the quick help!
