### ISSUE TITLE
Update Needed in Docker-Compose File Due to Path Change of subgen.py

### ISSUE THREAD

**Issue by mottiserver** [McCloudS/subgen#64]
Hello,

After a recent update, I encountered an issue where the Docker service failed to download subgen.py from its expected location, indicating a change in the file path. Could the Docker image be updated to accommodate these changes?

Thank you for your support.

**Comment by McCloudS** [comment]
Sorry, I meant to rebuild the docker files and it slipped my mind.  They should be up in about 10 minutes.  I re-organized the filesystem.

**Comment by mottiserver** [comment]
Much appreciated!
