### ISSUE TITLE
 CUDA failed with error out of memory

### ISSUE THREAD

**Issue by zorbaTheRainy** [McCloudS/subgen#72]
Get the error:

`INFO:root:Error processing or transcribing /movies/The Hollywood Revue of 1929 (1929)/The.Hollywood.Revue.of.1929.1929.DVDRip.XviD-BBM(iLC).avi: CUDA failed with error out of memory
`
compose file includes
`       - "TRANSCRIBE_DEVICE=gpu"
`
I request that if the transcription fails with this error, it falls back to using the `cpu`.

Otherwise, thanks so much for this program.  I started to try Whisper on my own and was not happy with the results.  Thank you so much for doing all the hard work for me.

**Comment by McCloudS** [comment]
Do you have a GPU mapped to your container?
I can try to work on checks to fail to CPU in the near term.

**Comment by zorbaTheRainy** [comment]
Oh yes.  
GPU works fine for other movies.

This one is just trouble.

It is only a GTX 1060 3Gb,  So, it isn't the best GPU.
But for other movies it works fine.

**Comment by hnorgaar** [comment]
I have same card as you and never had any fails with medium model. Dont go higher than that

**Comment by zorbaTheRainy** [comment]
I'll post my compose file

```
#docker-compose.yml
version: '2'
services:
  subgen:
    container_name: subgen
    tty: true
    image: mccloud/subgen
    environment:
       - "TRANSCRIBE_DEVICE=gpu"
       - "WHISPER_MODEL=medium"
       - "WHISPER_THREADS=4"
       - "PROCADDEDMEDIA=True"
       - "PROCMEDIAONPLAY=False"
       - "NAMESUBLANG=aa"
       - "SKIPIFINTERNALSUBLANG=eng"
       # - "PLEXTOKEN=plextoken"
       # - "PLEXSERVER=http://plexserver:32400"
       # - "JELLYFINTOKEN=token here"
       # - "JELLYFINSERVER=http://jellyfin:8096"
       - "WEBHOOKPORT=9010"
       - "CONCURRENT_TRANSCRIPTIONS=1"
       - "WORD_LEVEL_HIGHLIGHT=False"
       - "DEBUG=True"
       - "USE_PATH_MAPPING=False"
       - "PATH_MAPPING_FROM=/tv"
       - "PATH_MAPPING_TO=/Volumes/TV"
       - "CLEAR_VRAM_ON_COMPLETE=True"
       - "HF_TRANSFORMERS=False"
       - "HF_BATCH_SIZE=24"
       - "MODEL_PATH=./models"
       - "UPDATE=False"
       - "APPEND=False"
       - "TRANSCRIBE_FOLDERS=/tv|/movies"
       - "MONITOR=True"
    volumes:
       - 'D:\docker\subgen\tv:/tv'
       - 'D:\docker\subgen\movies:/movies'
       - 'D:\docker\subgen\models:/subgen/models'
    ports:
       - "9010:9010"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

**Comment by McCloudS** [comment]
There is no graceful way to handle this, as we have to know the architecture before loading the model.  Your best bet is using a lower model size or manually handling your OOM issues.  You could also try distil-medium.en, as it has a slightly smaller memory footprint.

**Comment by zorbaTheRainy** [comment]
OK
Thanks for looking into it.
