### ISSUE TITLE
distil-large-v3 - request

### ISSUE THREAD

**Issue by dandanarsk** [McCloudS/subgen#75]
Do you plan to add support for distil-large-v3? Thanks

**Comment by McCloudS** [comment]
`4 Mar 2024: Updated Dockerfile CUDA to 12.2.2 (From CTranslate2).  Added endpoint `/status` to return Subgen version.  Can also use distil models now!  See variables below!`

**Comment by McCloudS** [comment]
Sorry, I misread that as v2, didn’t know there was a v3.  Have you tried it to see if it can download it?

**Comment by dandanarsk** [comment]
Thank you

**Comment by dandanarsk** [comment]
Didn't work, tried to add it in the compose.yaml, but wont download.
Regards,
Dan Grosariu

**Comment by McCloudS** [comment]
`distil-large-v3` is now supported in the newest docker image.  Let me know if it doesn't work.
