### ISSUE TITLE
Cuda error： no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by xhzhu0628** [McCloudS/subgen#82]
recently I've been running CUDA programs in Docker on Unraid. 
I have successfully installed the NVIDIA driver in Unraid and confirmed the GPU version and CUDA version (12.4) using the nvidia-smi command within Docker. 

I'm using NVIDIA QUADRO K2200, CUDA 12.4

However, I'm still encountering an error when running the program: "no kernel image is available for execution on the device." 

What could be the possible reasons for this, and how can I resolve it?

**Comment by McCloudS** [comment]
How are you set up?  The docker container shouldn't let you run 12.4.  Subgen (which uses: Whisper, CTranslate2, and Stable-ts) won't work on 12.4, which is why you get that issue.  I am also running unraid.

nvidia-smi on the current subgen docker shows (just re-pulled it this morning): 
![image](https://github.com/McCloudS/subgen/assets/64094529/e2f3564f-349d-4b48-8b3e-05d74a4bb239)

**Comment by xhzhu0628** [comment]
<img width="493" alt="屏幕截图 2024-04-14 221423" src="https://github.com/McCloudS/subgen/assets/66295967/ba5f1973-fe48-4da6-8ebc-e017d9961adc">
<img width="452" alt="屏幕截图 2" src="https://github.com/McCloudS/subgen/assets/66295967/93bd0df2-de84-4e3e-8949-4849def91d61">
I just installed the NVIDIA Driver plugin yesterday. Here are screenshots of the version in the Unraid plugin and the nvidia-smi output in Docker.

**Comment by xhzhu0628** [comment]
> How are you set up? The docker container shouldn't let you run 12.4. Subgen (which uses: Whisper, CTranslate2, and Stable-ts) won't work on 12.4, which is why you get that issue. I am also running unraid.
> 
> nvidia-smi on the current subgen docker shows (just re-pulled it this morning): ![image](https://private-user-images.githubusercontent.com/64094529/322278639-e2f3564f-349d-4b48-8b3e-05d74a4bb239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMDQzMzMsIm5iZiI6MTcxMzEwNDAzMywicGF0aCI6Ii82NDA5NDUyOS8zMjIyNzg2MzktZTJmMzU2NGYtMzQ5ZC00YjQ4LThiM2UtMDVkNzRhNGJiMjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE0MTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkOTVjYTU3NjM1YzdhMGE3MTFmODg4OGUzNjMzOTY0MjQxZTcxNGE5MTE5YzUzZWYzOGRkZTcxYTgwYWMzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LZszaGTJI6M0UGPKS3SN8n2MsbmSRMxIc6nxixB6QmQ)

it seems that I should use v545.29.06 instead

**Comment by McCloudS** [comment]
Yeah, try downgrading versions.  Odd that my unraid doesn’t show your version, it shows me on the newest.

**Comment by xhzhu0628** [comment]
![image](https://github.com/McCloudS/subgen/assets/66295967/d5edb358-9c4f-46a4-9d4a-dd5e6f615720)
I downgraded the NVIDIA driver version, but the same error still occurs.  Maybe related to cuda compute capability？ I have no idea about it.

**Comment by McCloudS** [comment]
Ah, I think you’re right.  Per https://opennmt.net/CTranslate2/hardware_support.html: “NVIDIA GPUs with a Compute Capability greater or equal to 3.5” for CTranslate2 and the K2200 has 3.0.  I don’t think this will work for you.

Sorry.

**Comment by xhzhu0628** [comment]
> Ah, I think you’re right. Per https://opennmt.net/CTranslate2/hardware_support.html: “NVIDIA GPUs with a Compute Capability greater or equal to 3.5” for CTranslate2 and the K2200 has 3.0. I don’t think this will work for you.
> 
> Sorry.

https://developer.nvidia.com/cuda-gpus According to datasheet nvidia given, K2200 has 5.0 Compute Capability.  But it's weird compared to other similar-level cards...   I will change it and try again...

**Comment by McCloudS** [comment]
Yeah, I saw one nvidia document that said 3.0, but their official cuda page says 5.  Looks like this is a similar issue to https://github.com/ollama/ollama/issues/1756

I’m still reading it.

**Comment by McCloudS** [comment]
I’m finding conflicting stuff showing that compute 5.0/Maxwell was kind of left behind.  CTranslate2 doesn’t appear to build it for cuda12.

**Comment by McCloudS** [comment]
Asked around and see: https://github.com/OpenNMT/CTranslate2/issues/1666#issuecomment-2058390754

Compute 5.0 doesn't support CUDA 12, which CTranslate2 uses.  

Sorry.
