### ISSUE TITLE
cant find media folder not named "movies"

### ISSUE THREAD

**Issue by invisible-walrus** [McCloudS/subgen#9]
My Plex instance runs using one singular folder mounted to the container, then sub-directories to find its "tv" and "movies" folders. 

i mounted the subgen volume bind pointing at the same root folder but it cannot see any of the files inside. does it need to be pointing at two different folders, named "tv" and "movies"? and does plex also need to be looking for those two folders as well?

**Comment by McCloudS** [comment]
What do your volume binds look like for both Plex and subgen?  What do the subgen logs show?

**Comment by invisible-walrus** [comment]
Plex Bind: /mnt/Harmony:/Harmony
Subgen bind: /mnt/Harmony:/Harmony

also fails with "/mnt/Harmony/Plex Media/movies:/movies" and "/mnt/Harmony/Plex Media/tv shows:/tv"

Container logs are:
[_subgen_logs.txt](https://github.com/McCloudS/subgen/files/10783420/_subgen_logs.txt)

**Comment by McCloudS** [comment]
You have a 404 error in your log meaning your Plex API key is wrong, or you server/webhook address is wrong in Tautulli.  Re-read the instructions for setup.

**Comment by invisible-walrus** [comment]
Thanks! fixed the issue with the webhook, now getting a 200 result as expected. the logs dont show the processing of any files though, is that expected?
[_subgen_logs (1).txt](https://github.com/McCloudS/subgen/files/10792129/_subgen_logs.1.txt)

**Comment by McCloudS** [comment]
Dependant on your settings, whether you have trigger on add, play, or skip if existing internal sub.  Mine rarely runs (probably less than 5 times a week) as most stuff now has internal stuff embedded.

Easy way to test is enable proconplay and disable skip internal and just play something.

**Comment by invisible-walrus** [comment]
Solved, thank you so much!!
