### ISSUE TITLE
Writing over LRC files in Jellyfin

### ISSUE THREAD

**Issue by Tyler-Jay-Stevahn** [McCloudS/subgen#94]
Full disclosure, this might just be something I am doing wrong. 

I was thinking if you added a "If it doesn't exist" piece of code to these lines it should fix it.

"""
if isAudioFileExtension(file_extension) and lrc_for_audio_files:
            write_lrc(result, file_name + '.lrc')
"""

Into something like below
"""
if isAudioFileExtension(file_extension) and lrc_for_audio_files:
            if exists(): # the file already exists
                        pass
            else:
                        write_lrc(result, file_name + '.lrc')
"""

**Comment by McCloudS** [comment]
To be clear, it's overwriting the LRC files every time?  If so, I might be missing a check, similar to one I have for SRTs.

**Comment by McCloudS** [comment]
If my above statement is true, I may have fixed it.

https://github.com/McCloudS/subgen/commit/5b5fba3d82f047cbf3fd216dea92680a3d511bdb

**Comment by Tyler-Jay-Stevahn** [comment]
This solution works. If I wanted to get subtitles in Spanish instead of English, how would I do that?

**Comment by Tyler-Jay-Stevahn** [comment]
Oh that's a bummer, thanks for letting me know.
