### ISSUE TITLE
How to support multiple servers of the same kind (jellyfin)?

### ISSUE THREAD

**Issue by ZhengYuan-Public** [McCloudS/subgen#95]
Hi, I have two jellyfin servers hosted one on my NAS without GPU and another on a server with GPU. Is it possible to add both jellyfin servers? Thanks.

**Comment by McCloudS** [comment]
No, and likely won’t be added.  Best bet is to just run two instances of subgen.  

There isn’t much of a use case for running more than one of the same media server to warrant the effort to implement it.
